services:
  server:
    container_name: wangohan_server
    image: dasdasd443/wangohan-backend:latest
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
      - server_node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
  web:
    container_name: wangohan_web
    image: dasdasd443/wangohan-frontend:latest
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    depends_on:
      - server
volumes:
  web_node_modules:
  server_node_modules:
  wangohan_data:
  letsencrypt: 