services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=wangohan.info@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storeg=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`wangohan-traefik.victorchiong.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
  redis:
    image: redis:latest
    container_name: wangohan_redis
    restart: always
    ports:
      - 6379:6379
  postgres:
    container_name: wangohan_db
    image: postgres:latest
    env_file: ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - wangohan_data:/var/lib/postgresql/data    
      - ./backend/database:/data
    depends_on:
      - redis
  server:
    container_name: wangohan_server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
      - server_node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`wangohan.victorchiong.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolve=myresolver"
      - "traefik.http.services.server.loadbalancer.server.port=3001"
  web:
    container_name: wangohan_web
    build: 
      context: ./web
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    depends_on:
      - server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`wangohan-traefik.victorchiong.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolve=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
volumes:
  web_node_modules:
  server_node_modules:
  wangohan_data:
  letsencrypt: 